---
title: "Ryan's Selected Software Projects"
titleshort: "Ryan's Selected Software Projects"
author:
    -   |   
        Ryan Reece
#        Ryan Reece[^ReeceSCIPP]
#
#        [^ReeceSCIPP]: University of California, Santa Cruz
#
#    -   |   
#        Joe Coauthor[^JoeCoauthor]
#
#        [^JoeCoauthor]: Joe University, Joeville
authorshort: 'Ryan Reece'
date: 'March 1, 2013'
license: '&copy; 2014-2016 Ryan Reece. All rights reserved'
## ^ required meta-data ^ ----------------------------
#abstract: |
#    This is the abstract. This is the abstract. This is the abstract.
#    This is the abstract. This is the abstract. This is the abstract.
#    This is the abstract. This is the abstract. This is the abstract.
#
#    This is the second paragraph in the abstract.
#    This is the second paragraph in the abstract.
#    This is the second paragraph in the abstract.
## html options --------------------------------------
email: '![my email address](img/my_email.png) <br/> [reece.scipp.ucsc.edu](http://reece.scipp.ucsc.edu/)'
disqus: true
disqus_shortname: 'ryans-selected-software-projects'
description: "Ryan Reece's selected software projects on github"
keywords: 'Ryan Reece, markdown-memo, pyrootutils, rdrshell, roothtml, physics, LHC, ATLAS, python, data analysis, philosophy, science, philosophy of science'
google_analytics_tracking_id: 'UA-55199032-1'
#mathjax: true
## pdflatex options ----------------------------------
fontsize: '11pt'
fontfamily: 'mathpazo'
#linestretch: '1.1'
numbersections: true
spacing: '1.2'
geometry: 
    -   'paperwidth=8.5in'
    -   'paperheight=11in'
    -   'top=1in'
    -   'bottom=1in'
    -   'left=1.5in'
    -   'right=1.5in'
    -   'headheight=14pt'
    -   'headsep=\baselineskip'
fancyhdr: true
classoption:
    -   'openany'
    -   'twoside'
natbib: true
biblio-style: 'chicago'
...

