---
## required meta-data -------------------------------------
output: essays
title: 'Essays by Ryan Reece'
titleshort: 'Essays by Ryan Reece'
#subtitle: 'This is the subtitle'
authorshort: "Ryan Reece"
author1: Ryan Reece
email1: ryan.reece@cern.ch
homepage1: http://rreece.github.io/
affiliation1: University of California, Santa Cruz
#author2: Jane Coauthor
#email2: jane.coauthor@blah.com
#homepage2: http://jane.blah.com
#affiliation2: Joe University
#author3: Joe Coauthor
#email3: joe.coauthor@blah.com
#homepage3: http://joe.blah.com
#affiliation3: Joe University
author:
    -   |
        [Ryan Reece](http://rreece.github.io/)
#
#        [^ReeceSCIPP]: University of California, Santa Cruz / <ryan.reece@cern.ch> / <http://rreece.github.io/>
#    -   |
#        Jane Coauthor[^Jane]
#
#        [^Jane]: Joe University, Joeville / <jane@joe.edu> / <http://jane.joe.edu>
#    -   |
#        Joe Coauthor[^Joe]
#
#        [^Joe]: Joe University, Joeville / <joe@joe.edu> / <http://joe.joe.edu>
date: \today
#date: 'January 1, 2018'
#docid: EXAMPLE-DOC-000 # arXiv:1606.09150 # ATLAS-COM-PHYS-2010-200
draft: true
#license: ''
license: '&copy; 2015-2021 [Ryan Reece](http://rreece.github.io/). All rights reserved.'
#license: '<span class="copy-left">&copy;</span> 2015-2020 Ryan Reece. Licensed for sharing under [CC-BY-4.0](http://creativecommons.org/licenses/by/4.0/).'
#license: '<span class="copy-left">&copy;</span> 2020 The Authors. Licensed for sharing under [CC-BY-NC-SA-4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/).'
dorefs: true
submitted: ''
#submitted: 'Submitted to My Favorite Journal'
#submitted: 'Journal reference: *Phys. Rev. D 92*, 072001 (2015)'
## optional -----------------------------------------------
abstract: |
    These are drafts of my essays.  Please do not share them unless
    I have published them elsewhere, and in that case,
    share those versions.
#keywords: academic writing, blogging, digital humanities, LaTeX, Markdown, open publishing, open science, productivity, technical writing, typesetting, writing
citation-style: templates/apa-no-doi-no-issue-with-notes.csl
figureTitle: "Figure"
tableTitle: "Table"
figPrefix: "Figure"
eqnPrefix: "eq."
secPrefix: "Section"
tblPrefix: "Table"
## html options -------------------------------------------
css:
    -   'templates/markdown-memo.css'
    -   'https://use.fontawesome.com/releases/v5.2.0/css/all.css'
email: '<img class="email" src="img/my-email.png" alt="my email address"/>'
#email: '<img class="email" src="img/my-email-alt.png" alt="my email address"/>'
disqus_shortname: 'essays-2'
description: 'Essays by Ryan Reece'
favicon: 'img/markdown-favicon-196x196.png'
google_analytics_tracking_id: 'UA-55199032-1'
mathjax: true
navigation: true
#thumbnail: 'http://rreece.github.io/sw/markdown-memo/img/ATLAS-local-p0-vs-mH.png'
## pdflatex options ---------------------------------------
documentclass: 'article'
#documentclass: 'revtex4-1'
revtex: false
classoption:
#    -   'a4paper'
    -   'letterpaper'
    -   'openany'
    -   'twoside'
## revtex options ##
#    -   'aps'
#    -   'prl'
##    -   'aip'
##    -   'apl'
##    -   'twocolumn'
#    -   'preprint'
##    -   'reprint'
#    -   'nofootinbib'
#    -   'superscriptaddress'
#    -   'showkeys'
#extrapackages:
#    -   'jheppub'
fancyhdr: true
fontsize: '11pt'
fontfamily: 'mathpazo'
geometry: 
    -   'paperwidth=8.5in'
    -   'paperheight=11in'
    -   'top=1in'
    -   'bottom=1in'
    -   'left=1.25in'
    -   'right=1.25in'
    -   'headheight=14pt'
    -   'headsep=14pt'
hyperref: true
jhep: false
#linestretch: '1.1'
lof: false
lot: false
maketitle: false
numbersections: true
parskip: '11pt'
secnewpage: false
#spacing: '1.2'
toc: false
tocdepth: 3
...

