---
## required meta-data -------------------------------------
output: moving-naturalism-forward-2012-minutes
title: "Ryan's Moving Naturalism Forward 2012 Minutes"
titleshort: "Ryan's Moving Naturalism Forward 2012 Minutes"
author:
    -   |   
        [Ryan Reece](http://reece.scipp.ucsc.edu/)
#    -   |   
#        Ryan Reece[^ReeceSCIPP]
#
#        [^ReeceSCIPP]: University of California, Santa Cruz
#
#    -   |   
#        Joe Coauthor[^JoeCoauthor]
#
#        [^JoeCoauthor]: Joe University, Joeville
authorshort: 'Ryan Reece'
date: 'March 1, 2013'
draft: true
#license: ''
#license: '&copy; 2014-2016 Ryan Reece. All rights reserved.'
license: '<span class="copy-left">&copy;</span> 2013-2016 Ryan Reece. Licensed for sharing under [CC-BY-4.0](http://creativecommons.org/licenses/by/4.0/).'
dorefs: false
## optional -------------------------------------
#abstract: |
#    This is the abstract. This is the abstract. This is the abstract.
#    This is the abstract. This is the abstract. This is the abstract.
#    This is the abstract. This is the abstract. This is the abstract.
#
#    This is the second paragraph in the abstract.
#    This is the second paragraph in the abstract.
#    This is the second paragraph in the abstract.
#
#    *Keywords:* foundations of quantum mechanics, quantum field theory,
#    QFT, quantization, second quantization, wave-particle duality
figureTitle: "Figure"
tableTitle: "Table"
figPrefix: "Figure"
eqnPrefix: "eq."
tblPrefix: "Table"
## html options --------------------------------------
css: 'templates/markdown-memo-alt.css'
email: '![my email address](img/my-email-alt.png) <br/> [reece.scipp.ucsc.edu](http://reece.scipp.ucsc.edu/)'
disqus_shortname: 'ryans-moving-naturalism-forward-2012-minutes'
#description: 'Write a description of this webpage.'
#keywords: 'List, some, keywords, for, this, webpage'
google_analytics_tracking_id: 'UA-55199032-1'
#mathjax: true
navigation: true
## pdflatex options ----------------------------------
classoption:
    -   'openany'
    -   'twoside'
citation-style: 'templates/apa-no-doi-no-issue.csl'
fancyhdr: true
fontfamily: 'mathpazo'
fontsize: '11pt'
geometry: 
    -   'paperwidth=8.5in'
    -   'paperheight=11in'
    -   'top=1in'
    -   'bottom=1in'
    -   'left=1.25in'
    -   'right=1.25in'
    -   'headheight=14pt'
    -   'headsep=14pt'
#linestretch: '0.9'
lof: false
lot: false
maketitle: true
numbersections: true
parskip: '11pt'
spacing: '1.2'
toc: true
toc-depth: 3
...

