---
## required meta-data -------------------------------------
title: "Ryan's philosophy reading list"
titleshort: "Ryan's philosophy reading list"
#subtitle: "Subtitle"
author:
    -   |   
        [Ryan Reece](http://reece.scipp.ucsc.edu/)
#    -   |   
#        Ryan Reece[^ReeceSCIPP]
#
#        [^ReeceSCIPP]: University of California, Santa Cruz
#
#    -   |   
#        Joe Coauthor[^JoeCoauthor]
#
#        [^JoeCoauthor]: Joe University, Joeville
authorshort: "Ryan Reece"
date: 'August 1, 2014'
#license: '&copy; 2014-2016 Ryan Reece. All rights reserved'
license: '<span class="copy-left">&copy;</span> 2014-2016 Ryan Reece. Licensed for sharing under [CC-BY-4.0](http://creativecommons.org/licenses/by/4.0/)'
## optional -----------------------------------------------
#abstract: |
#    This is the abstract. This is the abstract. This is the abstract.
#    This is the abstract. This is the abstract. This is the abstract.
#    This is the abstract. This is the abstract. This is the abstract.
#
#    This is the second paragraph in the abstract.
#    This is the second paragraph in the abstract.
#    This is the second paragraph in the abstract.
figureTitle: "Figure"
tableTitle: "Table"
figPrefix: "Figure"
eqnPrefix: "eq."
tblPrefix: "Table"
## html options -------------------------------------------
email: '![my email address](img/my_email.png) <br/> [reece.scipp.ucsc.edu](http://reece.scipp.ucsc.edu/)'
disqus: true
disqus_shortname: 'ryans-philosophy-reading-list'
description: "Ryan Reece's philosophy reading list."
keywords: 'Ryan Reece, philosophy, philosophy of science, phyisics, phyisics of phyisics'
google_analytics_tracking_id: 'UA-55199032-1'
#mathjax: true
## pdflatex options ---------------------------------------
fontsize: '11pt'
fontfamily: 'mathpazo'
#linestretch: '1.1'
numbersections: true
spacing: '1.2'
geometry: 
    -   'paperwidth=8.5in'
    -   'paperheight=11in'
    -   'top=1in'
    -   'bottom=1in'
    -   'left=1.25in'
    -   'right=1.25in'
    -   'headheight=14pt'
    -   'headsep=14pt'
fancyhdr: true
classoption:
    -   'openany'
    -   'twoside'
natbib: true
biblio-style: 'chicago'
...

