---
title: "Ryan's Outline of Counter Apologetics"
titleshort: "Ryan's Outline of Counter Apologetics"
author:
    -   |
        Ryan Reece[^ReeceSCIPP]

        [^ReeceSCIPP]: University of California, Santa Cruz
authorshort: 'Ryan Reece'
date: 'January 1, 2014'
license: 'Licensed for sharing under [CC-BY-4.0](http://creativecommons.org/licenses/by/4.0/)'
# ^ required meta-data ^ ----------------------------
abstract: |
    \noindent This is the abstract. This is the abstract. This is the abstract.
    This is the abstract. This is the abstract. This is the abstract.
    This is the abstract. This is the abstract. This is the abstract.

    This is the second paragraph in the abstract.
    This is the second paragraph in the abstract.
    This is the second paragraph in the abstract.
# html options --------------------------------------
email: '![my email address](img/my_email.png) <br/> [reece.scipp.ucsc.edu](http://reece.scipp.ucsc.edu/)'
disqus: true
disqus_shortname: 'ryans-outline-of-counter-apologetics'
#description: 'Write a description of this webpage.'
#keywords: 'List, some, keywords, for, this, webpage'
google_analytics_tracking_id: 'UA-55199032-1'
#mathjax: true
# pdflatex options ----------------------------------
fontsize: '11pt'
fontfamily: 'mathpazo'
#linestretch: '1.1'
numbersections: true
spacing: '1.2'
geometry: 
    -   'paperwidth=8.5in'
    -   'paperheight=11in'
    -   'top=1in'
    -   'bottom=1in'
    -   'left=1.5in'
    -   'right=1.5in'
    -   'headheight=14pt'
    -   'headsep=\baselineskip'
fancyhdr: true
classoption:
    -   'openany'
    -   'twoside'
natbib: true
biblio-style: 'chicago'
...

