---
title: "Ryan's Outline of Counter Apologetics"
titleshort: "Ryan's Outline of Counter Apologetics"
subtitle: "An analysis of faith-based reasoning"
author:
    -   |   
        Ryan Reece[^ReeceSCIPP]

        [^ReeceSCIPP]: University of California, Santa Cruz
#
#    -   |   
#        Joe Coauthor[^JoeCoauthor]
#
#        [^JoeCoauthor]: Joe University, Joeville
authorshort: "Ryan Reece"
date: 'August 16, 2015'
license: '&copy; 2015-2016 Ryan Reece. All rights reserved'
## ^ required meta-data ^ ---------------------------------
#abstract: |
#    This is the abstract. This is the abstract. This is the abstract.
#    This is the abstract. This is the abstract. This is the abstract.
#    This is the abstract. This is the abstract. This is the abstract.
#
authorshort: 'Ryan Reece'
date: 'January 1, 2014'
license: 'Licensed for sharing under [CC-BY-4.0](http://creativecommons.org/licenses/by/4.0/)'
# ^ required meta-data ^ ----------------------------
#abstract: |
#    This is the abstract. This is the abstract. This is the abstract.
#    This is the abstract. This is the abstract. This is the abstract.
#    This is the abstract. This is the abstract. This is the abstract.
#
#    This is the second paragraph in the abstract.
#    This is the second paragraph in the abstract.
#    This is the second paragraph in the abstract.
# html options --------------------------------------
email: '![my email address](img/my_email.png) <br/> [reece.scipp.ucsc.edu](http://reece.scipp.ucsc.edu/)'
disqus: true
disqus_shortname: 'ryans-outline-of-counter-apologetics'
description: "Ryan Reece's outline of counter apologetics"
keywords: 'Ryan Reece, faith, counter apologetics, atheism, theism, agnosticism, religion, physics, philosophy, science, philosophy of science'
google_analytics_tracking_id: 'UA-55199032-1'
#mathjax: true
# pdflatex options ----------------------------------
fontsize: '11pt'
fontfamily: 'mathpazo'
#linestretch: '1.1'
numbersections: true
spacing: '1.2'
geometry: 
    -   'paperwidth=8.5in'
    -   'paperheight=11in'
    -   'top=1in'
    -   'bottom=1in'
    -   'left=1.5in'
    -   'right=1.5in'
    -   'headheight=14pt'
    -   'headsep=\baselineskip'
fancyhdr: true
classoption:
    -   'openany'
    -   'twoside'
natbib: true
biblio-style: 'chicago'
...

