---
## required meta-data -------------------------------------
output: doc
title: "Ryan's Outline of Counter Apologetics"
titleshort: "Ryan's Outline of Counter Apologetics"
subtitle: "An analysis of faith-based reasoning"
author:
    -   |   
        [Ryan Reece](http://reece.scipp.ucsc.edu/)
#    -   |   
#        Joe Coauthor[^JoeCoauthor]
#
#        [^JoeCoauthor]: Joe University, Joeville
authorshort: "Ryan Reece"
date: \today
draft: false
#license: ''
#license: '&copy; 2015-2016 Ryan Reece. All rights reserved.'
license: '<span class="copy-left">&copy;</span> 2014-2016 Ryan Reece. Licensed for sharing under [CC-BY-4.0](http://creativecommons.org/licenses/by/4.0/).'
dorefs: false
## optional -----------------------------------------------
#abstract: |
#    This is the abstract. This is the abstract. This is the abstract.
#    This is the abstract. This is the abstract. This is the abstract.
#    This is the abstract. This is the abstract. This is the abstract.
#    This is the abstract. This is the abstract. This is the abstract.
#
#    This is the second paragraph in the abstract.
#    This is the second paragraph in the abstract.
#    This is the second paragraph in the abstract.
figureTitle: "Figure"
tableTitle: "Table"
figPrefix: "Figure"
eqnPrefix: "eq."
tblPrefix: "Table"
## html options -------------------------------------------
css: 'templates/markdown-memo.css'
email: '![my email address](img/my_email.png) <br/> [reece.scipp.ucsc.edu](http://reece.scipp.ucsc.edu/)'
disqus_shortname: 'ryans-outline-of-counter-apologetics'
description: "Ryan Reece's outline of counter apologetics"
favicon: '/img/markdown-favicon-196x196.png'
google_analytics_tracking_id: 'UA-55199032-1'
keywords: 'Ryan Reece, faith, counter apologetics, atheism, theism, agnosticism, religion, physics, philosophy, science, philosophy of science'
#mathjax: true
navigation: true
#thumbnail: '/img/phil-of-science-v02.png'
# pdflatex options ----------------------------------
classoption:
    -   'openany'
    -   'twoside'
citation-style: 'templates/apa-no-doi-no-issue.csl'
fancyhdr: true
fontfamily: 'mathpazo'
fontsize: '11pt'
geometry: 
    -   'paperwidth=8.5in'
    -   'paperheight=11in'
    -   'top=1in'
    -   'bottom=1in'
    -   'left=1.25in'
    -   'right=1.25in'
    -   'headheight=14pt'
    -   'headsep=14pt'
#linestretch: '0.9'
lof: false
lot: false
maketitle: true
numbersections: true
parskip: '11pt'
spacing: '1.2'
toc: true
toc-depth: 3
...

