---
## required meta-data -------------------------------------
output: doc
title: "Ryan's Outline of Philosophy"
titleshort: "Ryan's Outline of Philosophy"
author:
    -   |   
        [Ryan Reece](http://reece.scipp.ucsc.edu/)
#    -   |   
#        Ryan Reece[^ReeceSCIPP]
#
#        [^ReeceSCIPP]: University of California, Santa Cruz
#
#    -   |   
#        Joe Coauthor[^JoeCoauthor]
#
#        [^JoeCoauthor]: Joe University, Joeville
authorshort: 'Ryan Reece'
date: 'January 3, 2016'
draft: false
#license: ''
license: '&copy; 2014-2016 Ryan Reece. All rights reserved.'
#license: '<span class="copy-left">&copy;</span> 2015-2016 Ryan Reece. Licensed for sharing under [CC-BY-4.0](http://creativecommons.org/licenses/by/4.0/).'
dorefs: false
## optional -------------------------------------
#abstract: |
#    This is the abstract. This is the abstract. This is the abstract.
#    This is the abstract. This is the abstract. This is the abstract.
#    This is the abstract. This is the abstract. This is the abstract.
#
#    This is the second paragraph in the abstract.
#    This is the second paragraph in the abstract.
#    This is the second paragraph in the abstract.
#
#    *Keywords:* quantum field theory, QFT, quantization, second quantization, wave-particle duality
figureTitle: "Figure"
tableTitle: "Table"
figPrefix: "Figure"
eqnPrefix: "eq."
tblPrefix: "Table"
# html options --------------------------------------
#css: 'templates/markdown-memo.css'
css: 'templates/markdown-memo-alt.css'
#email: '![my email address](img/my_email.png) <br/> [reece.scipp.ucsc.edu](http://reece.scipp.ucsc.edu/)'
email: '![my email address](img/my-email-alt.png) <br/> [reece.scipp.ucsc.edu](http://reece.scipp.ucsc.edu/)'
favicon: '/img/markdown-favicon-196x196.png'
disqus_shortname: 'ryans-outline-of-philosophy'
description: "Ryan Reece's outline of philosophy"
keywords: 'Ryan Reece, outline of philosophy, physics, data analysis, philosophy, science, philosophy of science'
google_analytics_tracking_id: 'UA-55199032-1'
mathjax: true
navigation: true
thumbnail: '/img/phil-of-science-v02.png'
# pdflatex options ----------------------------------
classoption:
    -   'openany'
    -   'twoside'
citation-style: 'templates/apa-no-doi-no-issue.csl'
fancyhdr: true
fontfamily: 'mathpazo'
fontsize: '11pt'
geometry: 
    -   'paperwidth=8.5in'
    -   'paperheight=11in'
    -   'top=1in'
    -   'bottom=1in'
    -   'left=1.25in'
    -   'right=1.25in'
    -   'headheight=14pt'
    -   'headsep=14pt'
#linestretch: '0.9'
lof: false
lot: false
maketitle: true
numbersections: true
parskip: '11pt'
spacing: '1.2'
toc: true
toc-depth: 3
...

